name: Build docker compose

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v1

    - name: Build the docker-compose stack
      run: docker-compose build
